const SEPARATOR_SPACED_SLASH = ' / '
const SEPARATOR_SPACED_FALLOW = ' -> '
const SEPARATOR_COMMA = ','
const SEPARATOR_SPACE = ' '

const SYMBOL_EMPTY = 'e'
const SYMBOL_END = '#'
const SYMBOL_NIHIL = ''

const STATE_START = 'Z'

export {
    SEPARATOR_SPACED_SLASH,
    SEPARATOR_SPACED_FALLOW,
    SEPARATOR_COMMA,
    SEPARATOR_SPACE,
    SYMBOL_EMPTY,
    SYMBOL_END,
    SYMBOL_NIHIL,
    STATE_START,
}