const SEPARATOR_SPACED_SLASH = ' / '
const SEPARATOR_SPACED_FALLOW = ' -> '
const SEPARATOR_COMMA = ','

const SYMBOL_EMPTY = 'e'
const SYMBOL_END = '#'
const SYMBOL_START = 'Z'

export {
    SEPARATOR_SPACED_SLASH,
    SEPARATOR_SPACED_FALLOW,
    SEPARATOR_COMMA,
    SYMBOL_EMPTY,
    SYMBOL_END,
    SYMBOL_START,
}