const SEPARATOR_SPACED_SLASH = ' / '
const SEPARATOR_SPACED_FALLOW = ' -> '
const SEPARATOR_COMMA = ','
const SEPARATOR_SPACE = ' '

const SYMBOL_EMPTY = 'e'
const SYMBOL_END = '#'
const SYMBOL_NIHIL = ''
const SYMBOL_TILDE = '~'

const STATE_START = '<Z>'
const STATE_REDUCE = 'R'

export {
    SEPARATOR_SPACED_SLASH,
    SEPARATOR_SPACED_FALLOW,
    SEPARATOR_COMMA,
    SEPARATOR_SPACE,
    SYMBOL_EMPTY,
    SYMBOL_END,
    SYMBOL_NIHIL,
    SYMBOL_TILDE,
    STATE_START,
    STATE_REDUCE,
}