export const fullGrammar = [
    "<Program> -> <Statement> <Program>",
    "<Program> -> <Statement>",
    "<Program> -> ",
    "<Statement> -> <Declaration>",
    "<Statement> -> <IfStatement>",
    "<Statement> -> <WhileStatement>",
    "<Statement> -> <FunctionDeclaration>",
    "<Statement> -> <FunctionCall>",
    "<Statement> -> <ReturnStatement>",
    "<Statement> -> <Assignment>",
    "<Declaration> -> let id : <Type> = <Expression> ;",
    "<Declaration> -> const id : <Type> = <Expression> ;",
    "<ReturnStatement> -> return <Expression> ;",
    "<Assignment> -> id = <Expression> ;",
    "<Assignment> -> <ArrayAccess> = <Expression> ;",
    "<ArrayAccess> -> id [ <ArrayIndex> ]",
    "<ArrayAccess> -> <ArrayAccess> [ <ArrayIndex> ]",
    "<ArrayIndex> -> <Expression>",
    "<IfStatement> -> if ( <Expression> ) { <Block> }",
    "<IfStatement> -> if ( <Expression> ) { <Block> } else { <Block> }",
    "<WhileStatement> -> while ( <Expression> ) { <Block> }",
    "<FunctionDeclaration> -> function id ( <Params> ) : <Type> { <Block> }",
    "<FunctionCall> -> id ( <Args> ) ;",
    "<Block> -> <Statement> <Block>",
    "<Block> -> <Statement>",
    "<Block> -> ",
    "<Params> -> id : <Type> <MoreParams>",
    "<Params> -> ",
    "<MoreParams> -> , id : <Type> <MoreParams>",
    "<MoreParams> -> ",
    "<Args> -> <Expression> <MoreArgs>",
    "<Args> -> ",
    "<MoreArgs> -> , <Expression> <MoreArgs>",
    "<MoreArgs> -> ",
    "<Type> -> <BaseType>",
    "<Type> -> <ArrayType>",
    "<BaseType> -> bool",
    "<BaseType> -> num",
    "<BaseType> -> string",
    "<BaseType> -> void",
    "<ArrayType> -> <BaseType> [ ]",
    "<ArrayType> -> <ArrayType> [ ]",
    "<Expression> -> <LogicExpr>",
    "<LogicExpr> -> <EqualityExpr> && <LogicExpr>",
    "<LogicExpr> -> <EqualityExpr>",
    "<EqualityExpr> -> <RelExpr> == <EqualityExpr>",
    "<EqualityExpr> -> <RelExpr> != <EqualityExpr>",
    "<EqualityExpr> -> <RelExpr>",
    "<RelExpr> -> <AddExpr> < <RelExpr>",
    "<RelExpr> -> <AddExpr> > <RelExpr>",
    "<RelExpr> -> <AddExpr> <= <RelExpr>",
    "<RelExpr> -> <AddExpr> >= <RelExpr>",
    "<RelExpr> -> <AddExpr>",
    "<AddExpr> -> <MulExpr> + <AddExpr>",
    "<AddExpr> -> <MulExpr> - <AddExpr>",
    "<AddExpr> -> <MulExpr>",
    "<MulExpr> -> <Factor> * <MulExpr>",
    "<MulExpr> -> <Factor>",
    "<Factor> -> - <Factor>",
    "<Factor> -> id",
    "<Factor> -> id ( <Args> )",
    "<Factor> -> <ArrayAccess>",
    "<Factor> -> ( <Expression> )",
    "<Factor> -> number",
    "<Factor> -> string",
    "<Factor> -> true",
    "<Factor> -> false",
    "<Factor> -> <ArrayLiteral>",
    "<ArrayMember> -> <Expression>",
    "<ArrayMember> -> <ArrayLiteral>",
    "<ArrayLiteral> -> [ <ArrayElements> ]",
    "<ArrayElements> -> <ArrayMember> <MoreArrayElements>",
    "<ArrayElements> -> ",
    "<MoreArrayElements> -> , <ArrayMember> <MoreArrayElements>",
    "<MoreArrayElements> -> "
]; 