export const grammar = [
    "<Program> -> <Statement> <Program>",
    "<Program> -> <Statement>",
    "<Statement> -> <Matched>",
    "<Statement> -> <Unmatched>",
    "<Matched> -> let id : <Type> = <Expression> ;",
    "<Matched> -> return <Expression> ;",
    "<Matched> -> if ( <Expression> ) <Matched> else <Matched>",
    "<Matched> -> if ( <Expression> ) { <Block> } else { <Block> }",
    "<Matched> -> while ( <Expression> ) <Matched>",
    "<Matched> -> while ( <Expression> ) { <Block> }",
    "<Matched> -> function id ( <Params> ) : <Type> <Matched>",
    "<Matched> -> function id ( <Params> ) : <Type> { <Block> }",
    "<Matched> -> id ( <Args> ) ;",
    "<Unmatched> -> if ( <Expression> ) <Statement>",
    "<Unmatched> -> if ( <Expression> ) <Matched> else <Unmatched>",
    "<Block> -> <Statement> <Block>",
    "<Block> -> <Statement>",
    "<Block> -> ",
    "<Params> -> id : <Type> <MoreParams>",
    "<Params> -> ",
    "<MoreParams> -> , id : <Type> <MoreParams>",
    "<MoreParams> -> ",
    "<Args> -> <Expression> <MoreArgs>",
    "<Args> -> ",
    "<MoreArgs> -> , <Expression> <MoreArgs>",
    "<MoreArgs> -> ",
    "<Type> -> bool",
    "<Type> -> number",
    "<Type> -> string",
    "<Expression> -> <LogicExpr>",
    "<LogicExpr> -> <EqualityExpr> && <LogicExpr>",
    "<LogicExpr> -> <EqualityExpr>",
    "<EqualityExpr> -> <RelExpr> == <EqualityExpr>",
    "<EqualityExpr> -> <RelExpr> != <EqualityExpr>",
    "<EqualityExpr> -> <RelExpr>",
    "<RelExpr> -> <AddExpr> < <RelExpr>",
    "<RelExpr> -> <AddExpr> > <RelExpr>",
    "<RelExpr> -> <AddExpr> <= <RelExpr>",
    "<RelExpr> -> <AddExpr> >= <RelExpr>",
    "<RelExpr> -> <AddExpr>",
    "<AddExpr> -> <MulExpr> + <AddExpr>",
    "<AddExpr> -> <MulExpr>",
    "<MulExpr> -> <Factor> * <MulExpr>",
    "<MulExpr> -> <Factor>",
    "<Factor> -> ( <Expression> )",
    "<Factor> -> number",
    "<Factor> -> string",
    "<Factor> -> bool",
    "<Factor> -> id",
    "<Factor> -> id ( <Args> )"
];