import fs from 'fs';
import path from 'path';
import { Lexer } from './lexer/lexer';
import { SLRParser } from './slr/slr';
import { SemanticAnalyzer } from './analyzer/analyzer';
import { SymbolTable } from './symbolTable/symbolTable';
import { CodeGenerator } from './generator/CodeGenerator';
import { fullGrammar } from './grammar/grammars';
import { Program } from './ast/entity';

function main() {
    // Этот скрипт теперь сам читает аргументы командной строки
    const args = process.argv.slice(2);
    if (args.length !== 1) {
        console.error("Использование: yarn compile program.txt");
        process.exit(1);
    }

    const sourcePath = args[0];
    if (!fs.existsSync(sourcePath)) {
        console.error(`Ошибка: Исходный файл не найден: ${sourcePath}`);
        process.exit(1);
    }

    const outputBasename = path.basename(sourcePath, path.extname(sourcePath));
    const outputPath = `${outputBasename}.prmbc`;

    try {
        const sourceCode = fs.readFileSync(sourcePath, 'utf-8');
        console.log(`Компиляция ${sourcePath}...`);
        
        console.log("1. Лексический анализ...");
        const lexer = new Lexer();
        const tokens = lexer.tokenize(sourceCode);
        console.log("✅ Лексер успешно создал токены.");

        console.log("\n2. Синтаксический анализ (парсинг)...");
        const parser = new SLRParser(fullGrammar, false); // false - отключить отладку таблицы
        const ast = parser.parse(tokens);
        if (typeof ast === 'string') {
            throw new Error(`Ошибка парсинга: ${ast}`);
        }
        console.log("✅ Парсер успешно построил AST.");
        console.log("Generated AST:", JSON.stringify(ast, null, 2));

        console.log("\n3. Семантический анализ...");
        const symbolTable = new SymbolTable();
        // Добавляем встроенные функции
        symbolTable.add('print', 'function', undefined, true, ['any'], 'void', true);
        symbolTable.add('println', 'function', undefined, true, ['any'], 'void', true);
        symbolTable.add('arrayLength', 'function', undefined, true, ['num[]'], 'num', true);
        symbolTable.add('getTimestamp', 'function', undefined, true, [], 'num', true);
        symbolTable.add('sqrt', 'function', undefined, true, ['num'], 'num', true);

        const analyzer = new SemanticAnalyzer(symbolTable);
        analyzer.analyze(ast);
        console.log("✅ Семантический анализ пройден успешно.");

        console.log("\n4. Генерация байт-кода...");
        const generator = new CodeGenerator(symbolTable);
        const bytecode = generator.generate(ast);
        console.log("✅ Генератор успешно создал байт-код.");
        console.log("--- Generated Bytecode ---");
        console.log(bytecode);
        console.log("--------------------------");

        fs.writeFileSync(outputPath, bytecode);

        console.log(`\n🎉 Успешно скомпилировано!`);
        console.log(`   Байт-код сохранен в: ${outputPath}`);
        console.log(`\nЧтобы запустить, используйте команду:`);
        console.log(`   prima/PVM.exe ${outputPath}`);

    } catch (e: any) {
        console.error("\n❌ Ошибка компиляции:", e.message);
        if (e.stack) {
            console.error(e.stack);
        }
        process.exit(1);
    }
}

main(); 